export const FILE_CHANGE = 'common/hero/FILE_CHANGE'
export const FILE_REMOVE = 'common/hero/FILE_REMOVE'
export const FILE_UPLOAD = 'common/hero/saga/FILE_UPLOAD'
export const START_UPLOAD = 'common/hero/START_UPLOAD'
export const FINISH_UPLOAD = 'common/hero/FINISH_UPLOAD'
export const FILE_UNDO = 'common/hero/saga/FILE_UNDO'
export const FINISH_FILE_UNDO = 'common/hero/FINISH_FILE_UNDO'
